### 1. Analysing raw extracted data

In [1]:
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

nasa_file = PROJECT_ROOT / "data/raw/nasa_power/nasa_power_raw.csv"
open_meteo_file = PROJECT_ROOT / "data/raw/open_meteo/open_meteo_raw.csv"
osm_file = PROJECT_ROOT / "data/raw/osm/locations_raw.csv"

nasa = pd.read_csv(nasa_file)
open_meteo = pd.read_csv(open_meteo_file)
osm = pd.read_csv(osm_file)

print("NASA POWER:", nasa.shape)
print("Open-Meteo:", open_meteo.shape)
print("OpenStreetMap:", osm.shape)

NASA POWER: (5117, 10)
Open-Meteo: (5117, 11)
OpenStreetMap: (7, 8)

In [2]:
nasa.head()

,date,T2M,RH2M,WS2M,ALLSKY_SFC_SW_DWN,location,latitude,longitude,state,region
0,2023-01-01,13.38,48.20,0.96,3.0706,Delhi,28.6139,77.209,Delhi,North
1,2023-01-02,11.70,52.39,1.16,1.8490,Delhi,28.6139,77.209,Delhi,North
2,2023-01-03,9.28,56.00,1.76,1.9087,Delhi,28.6139,77.209,Delhi,North
3,2023-01-04,8.71,59.91,1.50,1.9310,Delhi,28.6139,77.209,Delhi,North
4,2023-01-05,8.75,58.49,1.52,1.7275,Delhi,28.6139,77.209,Delhi,North

In [5]:
nasa.columns.tolist()

['date',
 'T2M',
 'RH2M',
 'WS2M',
 'ALLSKY_SFC_SW_DWN',
 'location',
 'latitude',
 'longitude',
 'state',
 'region']

In [6]:
nasa.info()

<class 'pandas.DataFrame'>
RangeIndex: 5117 entries, 0 to 5116
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               5117 non-null   str
 1   T2M                5117 non-null   float64
 2   RH2M               5117 non-null   float64
 3   WS2M               5117 non-null   float64
 4   ALLSKY_SFC_SW_DWN  5117 non-null   float64
 5   location           5117 non-null   str
 6   latitude           5117 non-null   float64
 7   longitude          5117 non-null   float64
 8   state              5117 non-null   str
 9   region             5117 non-null   str
dtypes: float64(6), str(4)
memory usage: 399.9 KB

In [7]:
nasa.describe(include="all")

,date,T2M,RH2M,WS2M,ALLSKY_SFC_SW_DWN,location,latitude,longitude,state,region
count,5117,5117.000000,5117.000000,5117.000000,5117.000000,5117,5117.000000,5117.000000,5117,5117
unique,731,NaN,NaN,NaN,NaN,7,NaN,NaN,6,7
top,2023-01-01,NaN,NaN,NaN,NaN,Delhi,NaN,NaN,Maharashtra,North
freq,7,NaN,NaN,NaN,NaN,731,NaN,NaN,1462,731
mean,NaN,25.421751,64.302259,1.989633,4.769930,NaN,22.490971,80.379557,NaN,NaN
std,NaN,5.467480,20.632010,1.111337,1.442217,NaN,4.993113,6.432311,NaN,NaN
min,NaN,7.950000,9.830000,0.190000,0.383000,NaN,12.971600,72.877700,NaN,NaN
25%,NaN,22.290000,48.980000,1.250000,3.831800,NaN,19.076000,75.787300,NaN,NaN
50%,NaN,26.210000,69.760000,1.830000,4.783900,NaN,22.572600,77.594600,NaN,NaN
75%,NaN,28.890000,81.510000,2.570000,5.830600,NaN,26.912400,88.363900,NaN,NaN
max,NaN,41.360000,96.010000,7.960000,8.197700,NaN,28.613900,91.736200,NaN,NaN

In [8]:
nasa.isnull().sum()

date                 0
T2M                  0
RH2M                 0
WS2M                 0
ALLSKY_SFC_SW_DWN    0
location             0
latitude             0
longitude            0
state                0
region               0
dtype: int64

In [9]:
nasa.isna().sum().sum()

np.int64(0)

In [10]:
nasa.duplicated().sum()

np.int64(0)

In [11]:
nasa.duplicated(
    subset=["date", "location"]
).sum()

np.int64(0)

In [12]:
nasa["date"] = pd.to_datetime(nasa["date"])

print("Start date:", nasa["date"].min())
print("End date:", nasa["date"].max())
print("Number of unique dates:", nasa["date"].nunique())

Start date: 2023-01-01 00:00:00
End date: 2024-12-31 00:00:00
Number of unique dates: 731

In [13]:
nasa["location"].unique()

<StringArray>
['Delhi', 'Mumbai', 'Nagpur', 'Kolkata', 'Bengaluru', 'Guwahati', 'Jaipur']
Length: 7, dtype: str

In [14]:
nasa["location"].value_counts()

location
Delhi        731
Mumbai       731
Nagpur       731
Kolkata      731
Bengaluru    731
Guwahati     731
Jaipur       731
Name: count, dtype: int64

In [15]:
open_meteo.head()

,date,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,wind_speed_10m_max,location,latitude,longitude,state,region
0,2023-01-01,18.3,7.9,12.5,0.0,8.7,Delhi,28.6139,77.209,Delhi,North
1,2023-01-02,18.2,6.3,12.2,0.0,9.2,Delhi,28.6139,77.209,Delhi,North
2,2023-01-03,16.6,6.0,10.6,0.0,9.7,Delhi,28.6139,77.209,Delhi,North
3,2023-01-04,16.5,5.4,9.7,0.0,11.2,Delhi,28.6139,77.209,Delhi,North
4,2023-01-05,15.4,5.4,8.9,0.0,10.2,Delhi,28.6139,77.209,Delhi,North

In [16]:
open_meteo.columns.tolist()

['date',
 'temperature_2m_max',
 'temperature_2m_min',
 'temperature_2m_mean',
 'precipitation_sum',
 'wind_speed_10m_max',
 'location',
 'latitude',
 'longitude',
 'state',
 'region']

In [17]:
open_meteo.info()

<class 'pandas.DataFrame'>
RangeIndex: 5117 entries, 0 to 5116
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date                 5117 non-null   str
 1   temperature_2m_max   5117 non-null   float64
 2   temperature_2m_min   5117 non-null   float64
 3   temperature_2m_mean  5117 non-null   float64
 4   precipitation_sum    5117 non-null   float64
 5   wind_speed_10m_max   5117 non-null   float64
 6   location             5117 non-null   str
 7   latitude             5117 non-null   float64
 8   longitude            5117 non-null   float64
 9   state                5117 non-null   str
 10  region               5117 non-null   str
dtypes: float64(7), str(4)
memory usage: 439.9 KB

In [18]:
open_meteo.isnull().sum()

date                   0
temperature_2m_max     0
temperature_2m_min     0
temperature_2m_mean    0
precipitation_sum      0
wind_speed_10m_max     0
location               0
latitude               0
longitude              0
state                  0
region                 0
dtype: int64

In [19]:
open_meteo.isna().sum().sum()

np.int64(0)

In [20]:
open_meteo.duplicated().sum()

np.int64(0)

In [21]:
open_meteo.duplicated(
    subset=["date", "location"]
).sum()

np.int64(0)

In [22]:
open_meteo["date"] = pd.to_datetime(open_meteo["date"])

print("Start date:", open_meteo["date"].min())
print("End date:", open_meteo["date"].max())
print("Number of unique dates:", open_meteo["date"].nunique())

Start date: 2023-01-01 00:00:00
End date: 2024-12-31 00:00:00
Number of unique dates: 731

In [23]:
open_meteo.groupby("location").size()

location
Bengaluru    731
Delhi        731
Guwahati     731
Jaipur       731
Kolkata      731
Mumbai       731
Nagpur       731
dtype: int64

In [4]:
osm.head()

,location,osm_latitude,osm_longitude,display_name,city,state,country,country_code
0,Delhi,28.632803,77.219771,"Delhi, India",NaN,Delhi,India,in
1,Mumbai,19.054999,72.869203,"Mumbai, Mumbai Suburban District, Maharashtra,...",Mumbai,Maharashtra,India,in
2,Nagpur,21.149813,79.082056,"Nagpur City, Nagpur Urban Taluka, Nagpur, Maha...",Nagpur City,Maharashtra,India,in
3,Kolkata,22.572646,88.363895,"Kolkata, Kolkata Metropolitan Area, Kolkata, W...",Kolkata,West Bengal,India,in
4,Bengaluru,12.976794,77.590082,"Bengaluru, Bangalore North, Bengaluru Urban, K...",Bengaluru,Karnataka,India,in

In [25]:
osm.columns.tolist()

['location',
 'osm_latitude',
 'osm_longitude',
 'display_name',
 'city',
 'state',
 'country',
 'country_code']

In [26]:
osm.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location       7 non-null      str
 1   osm_latitude   7 non-null      float64
 2   osm_longitude  7 non-null      float64
 3   display_name   7 non-null      str
 4   city           6 non-null      str
 5   state          7 non-null      str
 6   country        7 non-null      str
 7   country_code   7 non-null      str
dtypes: float64(2), str(6)
memory usage: 580.0 bytes

In [27]:
osm.isnull().sum()

location         0
osm_latitude     0
osm_longitude    0
display_name     0
city             1
state            0
country          0
country_code     0
dtype: int64

In [28]:
osm["location"].unique()

<StringArray>
['Delhi', 'Mumbai', 'Nagpur', 'Kolkata', 'Bengaluru', 'Guwahati', 'Jaipur']
Length: 7, dtype: str

#### OpenStreetMap contains 7 location records. All fields are complete except the city attribute for Delhi, which is missing even though the display_name and state fields identify it as Delhi.

In [29]:
osm[osm["city"].isna()]

,location,osm_latitude,osm_longitude,display_name,city,state,country,country_code
0,Delhi,28.632803,77.219771,"Delhi, India",NaN,Delhi,India,in

### Findings:
- NASA POWER: 5,117 records
- Open-Meteo: 5,117 records
- OpenStreetMap: 7 location records
- Weather data covers 2023–2024
- All 7 selected locations are represented in both weather datasets.
- The weather datasets have one daily record per location.
- OpenStreetMap has one missing city value for Delhi.


We inspected data types, missing values, duplicates, date ranges, and record distribution.